steps:
  - id: "build trainer image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - -c
      - |
        cd services/trainer 
        docker build -t gcr.io/${PROJECT_ID}/${_SERVICE_NAME} .

  - id: "push trainer image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "sh"
    args:
      - -c
      - |
        docker push gcr.io/${PROJECT_ID}/${_SERVICE_NAME}

substitutions:
  _SERVICE_NAME: trainer

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"
