steps:
  - id: "branch name"
    name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  - id: "freeze cloud function requirements"
    waitFor: ["-"]
    name: "fnndsc/python-poetry"
    entrypoint: "sh"
    args:
      - -c
      - |
        cd functions
        poetry export -f requirements.txt --output requirements.txt

  - id: "tf init"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -d "architecture/environments/$BRANCH_NAME/" ]; then
          cd architecture/environments/$BRANCH_NAME
          terraform init
        else
          for dir in architecture/environments/*/
          do 
            cd ${dir}   
            env=${dir%*/}
            env=${env#*/}
            echo ""
            echo "*************** TERRAFORM INIT ******************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform init || exit 1
            cd ../../../
          done
        fi
  # [START tf-plan]
  - id: "tf plan"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -d "architecture/environments/$BRANCH_NAME/" ]; then
          cd architecture/environments/$BRANCH_NAME
          terraform plan
        else
          for dir in architecture/environments/*/
          do 
            cd ${dir}   
            env=${dir%*/}
            env=${env#*/}  
            echo ""
            echo "*************** TERRAFOM PLAN ******************"
            echo "******* At environment: ${env} ********"
            echo "*************************************************"
            terraform plan || exit 1
            cd ../../../
          done
        fi
  # [END tf-plan]
  # [START tf-apply]
  - id: "tf apply"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -d "architecture/environments/$BRANCH_NAME/" ]; then
          cd architecture/environments/$BRANCH_NAME      
          terraform apply -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "Branch '$BRANCH_NAME' does not represent an official environment."
          echo "*******************************************************************************"
        fi
  # [END tf-apply]
