name: Cloud Functions Linter

on:
  push:
    branches:
      - main
    paths:
      - "functions/**.py"
  pull_request:
    branches:
      - main
    paths:
      - "functions/**.py"

jobs:
  lint:
    name: Run Black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./functions"
          version: "~= 22.3"
